<?php

use Illuminate\Database\Seeder;
use App\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dados = [

        	['provincia_id' => 1,'nome' => 'Ambriz'],
			['provincia_id' => 1,'nome' => 'Bula Atumba'],
			['provincia_id' => 1,'nome' => 'Caxito'],
			['provincia_id' => 1,'nome' => 'Dande'],
			['provincia_id' => 1,'nome' => 'Dembos'],
			['provincia_id' => 1,'nome' => 'Nambuangongo'],
			['provincia_id' => 1,'nome' => 'Pango Aluquem'],
			['provincia_id' => 2,'nome' => 'Balombo'],
			['provincia_id' => 2,'nome' => 'Baia Farta'],
			['provincia_id' => 2,'nome' => 'Benguela'],
			['provincia_id' => 2,'nome' => 'Bocoio'],
			['provincia_id' => 2,'nome' => 'Caimbambo'],
			['provincia_id' => 2,'nome' => 'Catumbela'],
			['provincia_id' => 2,'nome' => 'Chongoroi'],
			['provincia_id' => 2,'nome' => 'Cubal'],
			['provincia_id' => 2,'nome' => 'Ganda'],
			['provincia_id' => 2,'nome' => 'Lobito'],
			['provincia_id' => 3,'nome' => 'Andulo'],
			['provincia_id' => 3,'nome' => 'Camacupa'],
			['provincia_id' => 3,'nome' => 'Catabola'],
			['provincia_id' => 3,'nome' => 'Chinguar'],
			['provincia_id' => 3,'nome' => 'Chitembo'],
			['provincia_id' => 3,'nome' => 'Cuemba'],
			['provincia_id' => 3,'nome' =>  'Cunhinga'],
			['provincia_id' => 3,'nome' =>  'Kuito'],
			['provincia_id' => 3,'nome' =>  'Nharea'],
			['provincia_id' => 4,'nome' =>  'Belize'],
			['provincia_id' => 4,'nome' =>  'Buco-Zau'],
			['provincia_id' => 4,'nome' =>  'Cabinda'],
			['provincia_id' => 4,'nome' =>  'Cacongo'],
			['provincia_id' => 5,'nome' =>  'Calai'],
			['provincia_id' => 5,'nome' =>  'Cuchi'],
			['provincia_id' => 5,'nome' =>  'Cuito Cuanavale'],
			['provincia_id' => 5,'nome' =>  'Dirico'],
			['provincia_id' => 5,'nome' =>  'Longa'],
			['provincia_id' => 5,'nome' =>  'Mavinga'],
			['provincia_id' => 5,'nome' =>  'Menongue'],
			['provincia_id' => 5,'nome' =>  'Nancova'],
			['provincia_id' => 5,'nome' =>  'Rivungo'],
			['provincia_id' => 5,'nome' =>  'Cuangar'],
			['provincia_id' => 8,'nome' =>  'Cahama'],
			['provincia_id' => 8,'nome' =>  'Cuanhama'],
			['provincia_id' => 8,'nome' =>  'Curoca'],
			['provincia_id' => 8,'nome' =>  'Cuvelai'],
			['provincia_id' => 8,'nome' =>  'Namacunde'],
			['provincia_id' => 8,'nome' =>  'Ombandja'],
			['provincia_id' => 8,'nome' =>  'Ondjiva'],
			['provincia_id' => 9,'nome' =>  'Bailundo'],
			['provincia_id' => 9,'nome' =>  'Catchiungo'],
			['provincia_id' => 9,'nome' =>  'Caála'],
			['provincia_id' => 9,'nome' =>  'Ekunha'],
			['provincia_id' => 9,'nome' =>  'Huambo'],
			['provincia_id' => 9,'nome' =>  'Londuimbale'],
			['provincia_id' => 9,'nome' =>  'Longonjo'],
			['provincia_id' => 9,'nome' =>  'Mungo'],
			['provincia_id' => 9,'nome' =>  'Tchicala-Tcholoanga'],
			['provincia_id' => 9,'nome' =>  'Tchindjenje'],
			['provincia_id' => 9,'nome' =>  'Ucuma'],
			['provincia_id' => 10,'nome' => 'Caconda'],
			['provincia_id' => 10,'nome' => 'Cacula'],
			['provincia_id' => 10,'nome' => 'Caluquembe'],
			['provincia_id' => 10,'nome' => 'Chiange'],
			['provincia_id' => 10,'nome' => 'Chibia'],
			['provincia_id' => 10,'nome' => 'Chicomba'],
			['provincia_id' => 10,'nome' => 'Chipindo'],
			['provincia_id' => 10,'nome' => 'Cuvango'],
			['provincia_id' => 10,'nome' => 'Humpata'],
			['provincia_id' => 10,'nome' => 'Jamba'],
			['provincia_id' => 10,'nome' => 'Lubango'],
			['provincia_id' => 10,'nome' => 'Matala'],
			['provincia_id' => 10,'nome' => 'Quilengues'],
			['provincia_id' => 10,'nome' => 'Quipungo'],
			['provincia_id' => 6,'nome' => 'Ambaca'],
			['provincia_id' => 6,'nome' => 'Banga'],
			['provincia_id' => 6,'nome' => 'Bolongongo'],
			['provincia_id' => 6,'nome' => 'Cambambe'],
			['provincia_id' => 6,'nome' => 'Cazengo'],
			['provincia_id' => 6,'nome' => 'Golungo Alto'],
			['provincia_id' => 6,'nome' => 'Gonguembo'],
			['provincia_id' => 6,'nome' => 'Lucala'],
			['provincia_id' => 6,'nome' => 'N\'dalatando'],
			['provincia_id' => 6,'nome' => 'Quiculungo'],
			['provincia_id' => 6,'nome' => 'Samba Caju'],
			['provincia_id' => 7,'nome' => 'Amboim'],
			['provincia_id' => 7,'nome' => 'Cassongue'],
			['provincia_id' => 7,'nome' => 'Cela'],
			['provincia_id' => 7,'nome' => 'Conda'],
			['provincia_id' => 7,'nome' => 'Ebo'],
			['provincia_id' => 7,'nome' => 'Libolo'],
			['provincia_id' => 7,'nome' => 'Mussende'],
			['provincia_id' => 7,'nome' => 'Porto Amboim'],
			['provincia_id' => 7,'nome' => 'Quibala'],
			['provincia_id' => 7,'nome' => 'Quilenda'],
			['provincia_id' => 7,'nome' => 'Seles'],
			['provincia_id' => 7,'nome' => 'Sumbe'],
			['provincia_id' => 11,'nome' => 'Belas'],
			['provincia_id' => 11,'nome' => 'Cacuaco'],
			['provincia_id' => 11,'nome' => 'Cazenga'],
			['provincia_id' => 11,'nome' => 'Icolo e Bengo'],
			['provincia_id' => 11,'nome' => 'Luanda'],
			['provincia_id' => 11,'nome' => 'Quiçama'],
			['provincia_id' => 11,'nome' => 'Viana'],
			['provincia_id' => 12,'nome' => 'Cambulo'],
			['provincia_id' => 12,'nome' => 'Capenda-Camulemba'],
			['provincia_id' => 12,'nome' => 'Cuangula'],
			['provincia_id' => 12,'nome' => 'Chitato'],
			['provincia_id' => 12,'nome' => 'Cuango'],
			['provincia_id' => 12,'nome' => 'Cuílo'],
			['provincia_id' => 12,'nome' => 'Dundo'],
			['provincia_id' => 12,'nome' => 'Lubalo'],
			['provincia_id' => 12,'nome' => 'Lucapa'],
			['provincia_id' => 12,'nome' => 'Xa-Muteba'],
			['provincia_id' => 13,'nome' => 'Cacolo'],
			['provincia_id' => 13,'nome' => 'Dala'],
			['provincia_id' => 13,'nome' => 'Muconda'],
			['provincia_id' => 13,'nome' => 'Saurimo'],
			['provincia_id' => 14,'nome' => 'Cacuso'],
			['provincia_id' => 14,'nome' => 'Calandula'],
			['provincia_id' => 14,'nome' => 'Cambundi-Catembo'],
			['provincia_id' => 14,'nome' => 'Cangandala'],
			['provincia_id' => 14,'nome' => 'Caombo'],
			['provincia_id' => 14,'nome' => 'Cuaba Nzongo'],
			['provincia_id' => 14,'nome' => 'Cunda-Dia-Baze'],
			['provincia_id' => 14,'nome' => 'Luquembo'],
			['provincia_id' => 14,'nome' => 'Malange'],
			['provincia_id' => 14,'nome' => 'Marimba'],
			['provincia_id' => 14,'nome' => 'Massango'],
			['provincia_id' => 14,'nome' => 'Mucari'],
			['provincia_id' => 14,'nome' => 'Quela'],
			['provincia_id' => 14,'nome' => 'Quirima'],
			['provincia_id' => 15, 'nome' => 'Alto Zambeze'],
			['provincia_id' => 15, 'nome' => 'Bundas'],
			['provincia_id' => 15, 'nome' => 'Camanongue'],
			['provincia_id' => 15, 'nome' => 'Leua'],
			['provincia_id' => 15, 'nome' => 'Luau'],
			['provincia_id' => 15, 'nome' => 'Luacano'],
			['provincia_id' => 15, 'nome' => 'Luchazes'],
			['provincia_id' => 15, 'nome' => 'Luena'],
			['provincia_id' => 15, 'nome' => 'Lumeje'],
			['provincia_id' => 15, 'nome' => 'Moxico'],
			['provincia_id' => 16, 'nome' => 'Bibala'],
			['provincia_id' => 16, 'nome' => 'Camucuio'],
			['provincia_id' => 16, 'nome' => 'Moçâmides'],
			['provincia_id' => 16, 'nome' => 'Tombua'],
			['provincia_id' => 16, 'nome' => 'Virei'],
			['provincia_id' => 17, 'nome' => 'Alto Cauale'],
			['provincia_id' => 17, 'nome' => 'Ambuila'],
			['provincia_id' => 17, 'nome' => 'Bembe'],
			['provincia_id' => 17, 'nome' => 'Buengas'],
			['provincia_id' => 17, 'nome' => 'Bungo'],
			['provincia_id' => 17, 'nome' => 'Damba'],
			['provincia_id' => 17, 'nome' => 'Macocola'],
			['provincia_id' => 17, 'nome' => 'Milunga'],
			['provincia_id' => 17, 'nome' => 'Mucaba'],
			['provincia_id' => 17, 'nome' => 'Negage'],
			['provincia_id' => 17, 'nome' => 'Puri'],
			['provincia_id' => 17, 'nome' => 'Quimbele'],
			['provincia_id' => 17, 'nome' => 'Quitexe'],
			['provincia_id' => 17, 'nome' => 'Sanza'],
			['provincia_id' => 17, 'nome' => 'Pombo'],
			['provincia_id' => 17, 'nome' => 'Songo'],
			['provincia_id' => 17, 'nome' => 'Uige'],
			['provincia_id' => 17, 'nome' => 'Zombo'],
			['provincia_id' => 18, 'nome' => 'Cuimba'],
			['provincia_id' => 18, 'nome' => 'M\'Banza Kongo'],
			['provincia_id' => 18, 'nome' => 'Noqui'],
			['provincia_id' => 18, 'nome' => 'N\'Zeto'],
			['provincia_id' => 18, 'nome' => 'Soyo'],
			['provincia_id' => 18, 'nome' => 'Tomboco']
        ];

        foreach ($dados as $key => $value){
        	
        	Municipio::create($value);

        	echo "Municipio ".$value['nome']." Criado!";
        }
    }
}
